### ISSUE TITLE
Use http://cquiroz.github.io/scala-java-time/ instead of scalajs-javatime for better java time support

### ISSUE THREAD

**Issue by kalejami** [japgolly/test-state#81]
Tried to use test-state for an application which is using LocalDateTime in the frontend. Getting linking errors from scalajs-javatime. Cquiroz provides a better support for the java time lib.

Or maybe make it possible to use any kind of java time lib? 🤔

**Comment by japgolly** [comment]
Hey @kalejami . Thanks for bringing this up and raising a PR. Let me get back to you over the weekend

**Comment by kalejami** [comment]
@japgolly Another approach would be to make the java.time Dependency a provided one. Seems to work to because both scalajs-javatime and cquiroz/scala-java-time use the same symbols.

**Comment by japgolly** [comment]
@kalejami Yeah maybe that is the best idea. I don't want to lock anyone in.

As a temporary workaround, are you able to exclude scalajs-javatime as a transitive dependency?

**Comment by kalejami** [comment]
@japgolly Fine with me :)

**Comment by kalejami** [comment]
@japgolly I changed the PR. scalajs-javatime is now provided

**Comment by japgolly** [comment]
Sorry about the delay @kalejami ; busy times. I've merged the PR and I believe we're all good now. Please reopen if there are any problems and thanks for raising this.
